// -*- C++ -*-
//
// generated by wxGlade
//
// Example for compiling a single file project under Linux using g++:
//  g++ MyApp.cpp $(wx-config --libs) $(wx-config --cxxflags) -o MyApp
//
// Example for compiling a multi file project under Linux using g++:
//  g++ main.cpp $(wx-config --libs) $(wx-config --cxxflags) -o MyApp Dialog1.cpp Frame1.cpp
//

#ifndef PREFERENCES_H
#define PREFERENCES_H

#include <wx/wx.h>
#include <wx/image.h>

// begin wxGlade: ::dependencies
#include <wx/hyperlink.h>
#include <wx/spinctrl.h>
// end wxGlade

// begin wxGlade: ::extracode
// end wxGlade


class PreferencesWindow: public wxDialog {
public:
    // begin wxGlade: PreferencesWindow::ids
    // end wxGlade

    PreferencesWindow(wxWindow* parent, wxWindowID id, const wxString& title, const wxPoint& pos=wxDefaultPosition, const wxSize& size=wxDefaultSize, long style=wxDEFAULT_DIALOG_STYLE);

private:

protected:
    // begin wxGlade: PreferencesWindow::attributes
    wxTextCtrl* server;
    wxTextCtrl* port;
    wxTextCtrl* api_key;
    wxHyperlinkCtrl* hyperlink_1;
    wxSpinCtrlDouble* min_reconnect_time;
    wxSpinCtrlDouble* max_reconnect_time;
    wxButton* button_SAVE;
    wxButton* button_CANCEL;
    // end wxGlade
}; // wxGlade: end class


#endif // PREFERENCES_H
